"""Pure controller engine public API.

This package must stay independent of Home Assistant.  Integration adapters may
translate HA states/actions at the boundary, then pass these immutable values to
the engine for deterministic planning and allocation.
"""

from .accounting import (
    AccountingInterval,
    EnergyProvenance,
    RuntimeAccounting,
    record_interval,
    reset_daily_accounting,
)
from .arbitrator import ArbitrationInput, ArbitrationResult, SiteArbitrator
from .clock import Clock, FixedClock, PersistedTimer, SystemClock
from .learning import (
    LearningPolicy,
    LearningSample,
    LearningState,
    LearningUpdate,
    estimate_for,
    reset_learning,
    set_learning_frozen,
    update_learning,
)
from .models import (
    CommandAction,
    CommandProposal,
    CommandSource,
    CompletionMode,
    CompletionTarget,
    DecisionEvent,
    EnergySource,
    ForecastPoint,
    LearningEstimate,
    LoadConfigV1,
    LoadKind,
    LoadRequest,
    LoadSnapshot,
    LoadState,
    Override,
    OverrideMode,
    PlanInterval,
    ReasonCode,
    ScheduleWindow,
    SiteAllocation,
    SiteConfigV1,
    SitePowerSnapshot,
)
from .planner import (
    DeterministicPlanner,
    LoadPlanResult,
    PlannerSettings,
    PlanningInput,
    PlanResult,
    PlanSlot,
    latest_safe_start_at,
    plan_24h,
)
from .schedule import (
    OperationalDay,
    ScheduleBoundary,
    ScheduleInterval,
    active_windows_at,
    interval_for_local_date,
    is_active_at,
    next_transition_at,
    operational_day_bounds,
    operational_day_for,
    resolve_local_datetime,
)
from .simulation import (
    SIMULATION_VERSION,
    SimulationReport,
    SimulationScenario,
    SimulationSlot,
    SimulationSuiteReport,
    default_scenarios,
    run_default_suite,
    run_scenario,
    run_suite,
)
from .solar import SolarAction, SolarDecision, SolarPolicy, SolarQualificationState, evaluate_solar
from .state import CommandAuthorization, StateDecision, authorize_command, derive_load_state
from .tariff import (
    EnergyCostBreakdown,
    PriceInterval,
    PriceUnit,
    TariffTimeline,
    cost_for_energy,
    normalize_price,
    split_interval_cost,
)

__all__ = [
    "AccountingInterval",
    "ArbitrationInput",
    "ArbitrationResult",
    "Clock",
    "CommandAction",
    "CommandAuthorization",
    "CommandProposal",
    "CommandSource",
    "CompletionMode",
    "CompletionTarget",
    "DecisionEvent",
    "DeterministicPlanner",
    "EnergyCostBreakdown",
    "EnergyProvenance",
    "EnergySource",
    "FixedClock",
    "ForecastPoint",
    "LearningEstimate",
    "LearningPolicy",
    "LearningSample",
    "LearningState",
    "LearningUpdate",
    "LoadConfigV1",
    "LoadKind",
    "LoadPlanResult",
    "LoadRequest",
    "LoadSnapshot",
    "LoadState",
    "OperationalDay",
    "Override",
    "OverrideMode",
    "PersistedTimer",
    "PlanInterval",
    "PlanResult",
    "PlanSlot",
    "PlannerSettings",
    "PlanningInput",
    "PriceInterval",
    "PriceUnit",
    "ReasonCode",
    "RuntimeAccounting",
    "ScheduleBoundary",
    "ScheduleInterval",
    "ScheduleWindow",
    "SIMULATION_VERSION",
    "SiteAllocation",
    "SiteArbitrator",
    "SiteConfigV1",
    "SitePowerSnapshot",
    "SolarAction",
    "SolarDecision",
    "SolarPolicy",
    "SolarQualificationState",
    "SimulationReport",
    "SimulationScenario",
    "SimulationSlot",
    "SimulationSuiteReport",
    "StateDecision",
    "SystemClock",
    "TariffTimeline",
    "active_windows_at",
    "authorize_command",
    "cost_for_energy",
    "derive_load_state",
    "default_scenarios",
    "estimate_for",
    "evaluate_solar",
    "interval_for_local_date",
    "is_active_at",
    "latest_safe_start_at",
    "next_transition_at",
    "normalize_price",
    "operational_day_bounds",
    "operational_day_for",
    "plan_24h",
    "record_interval",
    "reset_daily_accounting",
    "reset_learning",
    "resolve_local_datetime",
    "run_default_suite",
    "run_scenario",
    "run_suite",
    "set_learning_frozen",
    "split_interval_cost",
    "update_learning",
]
